export interface Poligono {
  ciudad: string;
  nivel_poligono: string;
  descripcion: string;
  clasificacionId: number;
}

export const LISTA_POLIGONOS: Poligono[] = [
  { ciudad: "Acapulco", nivel_poligono: "Plata", descripcion: "Acapulco Norte", clasificacionId: 2 },
  { ciudad: "Acapulco", nivel_poligono: "Plata", descripcion: "Acapulco Sur", clasificacionId: 2 },
  { ciudad: "Aguascalientes", nivel_poligono: "Oro", descripcion: "Aguascalientes Sur", clasificacionId: 3 },
  { ciudad: "Aguascalientes", nivel_poligono: "Plata", descripcion: "Aguascalientes Este", clasificacionId: 2 },
  { ciudad: "Aguascalientes", nivel_poligono: "Oro", descripcion: "Aguascalientes Norte", clasificacionId: 3 },
  { ciudad: "Ahome", nivel_poligono: "Plata", descripcion: "Ahome", clasificacionId: 2 },
  { ciudad: "Arandas", nivel_poligono: "Plata", descripcion: "Arandas", clasificacionId: 2 },
  { ciudad: "CDMX", nivel_poligono: "Plata", descripcion: "Azcapotzalgo, Cdmx", clasificacionId: 2 },
  { ciudad: "Ensenada", nivel_poligono: "Oro", descripcion: "Baja Norte Ensenada", clasificacionId: 3 },
  { ciudad: "San José del Cabo", nivel_poligono: "Plata", descripcion: "Baja sur Norte San José del Cabo", clasificacionId: 2 },
  { ciudad: "Cabo San Lucas", nivel_poligono: "Bronce", descripcion: "Baja Sur Cabo San Lucas Centro", clasificacionId: 1 },
  { ciudad: "Cabo San Lucas", nivel_poligono: "Plata", descripcion: "Baja Sur Cabo San Lucas Este", clasificacionId: 2 },
  { ciudad: "Cabo San Lucas", nivel_poligono: "Plata", descripcion: "Baja Sur Cabo San Lucas Norte", clasificacionId: 2 },
  { ciudad: "Cabo San Lucas", nivel_poligono: "Oro", descripcion: "Baja Sur Cabo San Lucas Sur", clasificacionId: 3 },
  { ciudad: "San José del Cabo", nivel_poligono: "Bronce", descripcion: "Baja sur Centro San José del Cabo", clasificacionId: 1 },
  { ciudad: "Loreto", nivel_poligono: "Plata", descripcion: "Baja Sur Loreto", clasificacionId: 2 },
  { ciudad: "San José del Cabo", nivel_poligono: "Plata", descripcion: "Baja sur Sur San Jose del Cabo", clasificacionId: 2 },
  { ciudad: "Boca del rio", nivel_poligono: "Oro", descripcion: "Boca del rio", clasificacionId: 3 },
  { ciudad: "Campeche", nivel_poligono: "Plata", descripcion: "Campeche", clasificacionId: 2 },
  { ciudad: "Cancún", nivel_poligono: "Oro", descripcion: "Cancún", clasificacionId: 3 },
  { ciudad: "Cd. Juárez", nivel_poligono: "Plata", descripcion: "CD. JUAREZ", clasificacionId: 2 },
  { ciudad: "Cd. Madero", nivel_poligono: "Plata", descripcion: "Cd. Madero", clasificacionId: 2 },
  { ciudad: "Cd. Victoria", nivel_poligono: "Plata", descripcion: "Cd. Victoria", clasificacionId: 2 },
  { ciudad: "Celaya", nivel_poligono: "Plata", descripcion: "Celaya Centro", clasificacionId: 2 },
  { ciudad: "Celaya", nivel_poligono: "Plata", descripcion: "Celaya Este", clasificacionId: 2 },
  { ciudad: "Celaya", nivel_poligono: "Plata", descripcion: "Celaya Noroeste", clasificacionId: 2 },
  { ciudad: "Celaya", nivel_poligono: "Plata", descripcion: "Celaya Norte", clasificacionId: 2 },
  { ciudad: "Celaya", nivel_poligono: "Plata", descripcion: "Celaya Sur", clasificacionId: 2 },
  { ciudad: "Chetumal", nivel_poligono: "Plata", descripcion: "Chetumal", clasificacionId: 2 },
  { ciudad: "Chihuahua", nivel_poligono: "Platino", descripcion: "Chihuahua Centro", clasificacionId: 4 },
  { ciudad: "Chihuahua", nivel_poligono: "Plata", descripcion: "Chihuahua Norte", clasificacionId: 2 },
  { ciudad: "Chihuahua", nivel_poligono: "Bronce", descripcion: "Chihuahua Sur", clasificacionId: 1 },
  { ciudad: "Chilpancingo", nivel_poligono: "Plata", descripcion: "Chilpancingo", clasificacionId: 2 },
  { ciudad: "CDMX", nivel_poligono: "Plata", descripcion: "Coapa Oriente, Cdmx", clasificacionId: 2 },
  { ciudad: "CDMX", nivel_poligono: "Oro", descripcion: "Coapa Poniente, Cdmx", clasificacionId: 3 },
  { ciudad: "Coatepec", nivel_poligono: "Bronce", descripcion: "Coatepec", clasificacionId: 1 },
  { ciudad: "Coatzacoalcos", nivel_poligono: "Plata", descripcion: "Coatzacoalcos", clasificacionId: 2 },
  { ciudad: "Colima", nivel_poligono: "Oro", descripcion: "Colima Polígono Este", clasificacionId: 3 },
  { ciudad: "Colima", nivel_poligono: "Plata", descripcion: "colima Polígono Oeste", clasificacionId: 2 },
  { ciudad: "Comitan", nivel_poligono: "Plata", descripcion: "Comitan", clasificacionId: 2 },
  { ciudad: "Cordova", nivel_poligono: "Plata", descripcion: "Cordova", clasificacionId: 2 },
  { ciudad: "Cuauhtémoc", nivel_poligono: "Plata", descripcion: "Cuauhtémoc", clasificacionId: 2 },
  { ciudad: "Culiacán", nivel_poligono: "Oro", descripcion: "Culiacán Norte", clasificacionId: 3 },
  { ciudad: "Culiacán", nivel_poligono: "Plata", descripcion: "Culiacán Sur", clasificacionId: 2 },
  { ciudad: "Delicias", nivel_poligono: "Bronce", descripcion: "Delicias", clasificacionId: 1 },
  { ciudad: "Durango", nivel_poligono: "Plata", descripcion: "Durango Cap. Oriente", clasificacionId: 2 },
  { ciudad: "Durango", nivel_poligono: "Oro", descripcion: "Durango Cap. Poniente", clasificacionId: 3 },
  { ciudad: "Fresnillo", nivel_poligono: "Plata", descripcion: "Fresnillo", clasificacionId: 2 },
  { ciudad: "Gomez Palacio", nivel_poligono: "Plata", descripcion: "Goméz Palacio", clasificacionId: 2 },
  { ciudad: "Guadalajara", nivel_poligono: "Platino", descripcion: "Guadalajara Centro", clasificacionId: 4 },
  { ciudad: "Guadalajara", nivel_poligono: "Oro", descripcion: "Guadalajara Este", clasificacionId: 3 },
  { ciudad: "Guadalajara", nivel_poligono: "Platino", descripcion: "Guadalajara Este", clasificacionId: 4 },
  { ciudad: "Guadalajara", nivel_poligono: "Oro", descripcion: "Guadalajara Noreste", clasificacionId: 3 },
  { ciudad: "Guadalajara", nivel_poligono: "Platino", descripcion: "Guadalajara Norte", clasificacionId: 4 },
  { ciudad: "Guadalajara", nivel_poligono: "Oro", descripcion: "Guadalajara sur", clasificacionId: 3 },
  { ciudad: "Guadalupe", nivel_poligono: "Plata", descripcion: "Guadalupe", clasificacionId: 2 },
  { ciudad: "Guasave", nivel_poligono: "Bronce", descripcion: "Guasave", clasificacionId: 1 },
  { ciudad: "Hermosillo", nivel_poligono: "Plata", descripcion: "Hermosillo Norte", clasificacionId: 2 },
  { ciudad: "Hermosillo", nivel_poligono: "Plata", descripcion: "Hermosillo Sur", clasificacionId: 2 },
  { ciudad: "Heroica Cárdenas", nivel_poligono: "Bronce", descripcion: "Heroica Cárdenas", clasificacionId: 1 },
  { ciudad: "Huejutla", nivel_poligono: "Bronce", descripcion: "Huejutla", clasificacionId: 1 },
  { ciudad: "Irapuato", nivel_poligono: "Plata", descripcion: "Irapuato Sur", clasificacionId: 2 },
  { ciudad: "Irapuato", nivel_poligono: "Plata", descripcion: "Irapuato Este", clasificacionId: 2 },
  { ciudad: "Irapuato", nivel_poligono: "Plata", descripcion: "Irapuato Noroeste", clasificacionId: 2 },
  { ciudad: "Irapuato", nivel_poligono: "Plata", descripcion: "Irapuato Norte", clasificacionId: 2 },
  { ciudad: "Irapuato", nivel_poligono: "Plata", descripcion: "Irapuato Sureste", clasificacionId: 2 },
  { ciudad: "CDMX", nivel_poligono: "Plata", descripcion: "Iztapalapa, Cdmx", clasificacionId: 2 },
  { ciudad: "Jeréz", nivel_poligono: "Bronce", descripcion: "Jeréz", clasificacionId: 1 },
  { ciudad: "Juchitán", nivel_poligono: "Plata", descripcion: "Juchitán", clasificacionId: 2 },
  { ciudad: "León", nivel_poligono: "Plata", descripcion: "Leon Polígono Centro Sur", clasificacionId: 2 },
  { ciudad: "León", nivel_poligono: "Plata", descripcion: "Leon Polígono Oeste", clasificacionId: 2 },
  { ciudad: "León", nivel_poligono: "Bronce", descripcion: "Leon Polígono Bronce Sureste", clasificacionId: 1 },
  { ciudad: "León", nivel_poligono: "Oro", descripcion: "Leon Polígono Centro Norte", clasificacionId: 3 },
  { ciudad: "León", nivel_poligono: "Plata", descripcion: "Leon Polígono Este", clasificacionId: 2 },
  { ciudad: "León", nivel_poligono: "Platino", descripcion: "Leon Polígono Norte", clasificacionId: 4 },
  { ciudad: "León", nivel_poligono: "Oro", descripcion: "Leon Polígono Sur", clasificacionId: 3 },
  { ciudad: "León", nivel_poligono: "Bronce", descripcion: "Leon Polígono Suroeste", clasificacionId: 1 },
  { ciudad: "Loreto Zac.", nivel_poligono: "Bronce", descripcion: "Loreto Zac.", clasificacionId: 1 },
  { ciudad: "Matamoros", nivel_poligono: "Bronce", descripcion: "Matamoros", clasificacionId: 1 },
  { ciudad: "Mazatlán", nivel_poligono: "Oro", descripcion: "Mazatlán", clasificacionId: 3 },
  { ciudad: "Merida", nivel_poligono: "Oro", descripcion: "Merida Norte", clasificacionId: 3 },
  { ciudad: "Merida", nivel_poligono: "Plata", descripcion: "Merida Sur", clasificacionId: 2 },
  { ciudad: "Edo. Mex", nivel_poligono: "Platino", descripcion: "Metepec", clasificacionId: 4 },
  { ciudad: "Minatitlan", nivel_poligono: "Bronce", descripcion: "Minatitlan", clasificacionId: 1 },
  { ciudad: "Monclova", nivel_poligono: "Plata", descripcion: "Monclova", clasificacionId: 2 },
  { ciudad: "Morelia", nivel_poligono: "Oro", descripcion: "Morelia Centro Oeste", clasificacionId: 3 },
  { ciudad: "Morelia", nivel_poligono: "Platino", descripcion: "Morelia Este", clasificacionId: 4 },
  { ciudad: "Morelia", nivel_poligono: "Plata", descripcion: "Morelia Noreste", clasificacionId: 2 },
  { ciudad: "Morelia", nivel_poligono: "Oro", descripcion: "Morelia Noroeste", clasificacionId: 3 },
  { ciudad: "Morelia", nivel_poligono: "Plata", descripcion: "Morelia Sur", clasificacionId: 2 },
  { ciudad: "Morelia", nivel_poligono: "Oro", descripcion: "Morelia Sureste", clasificacionId: 3 },
  { ciudad: "Cuautla", nivel_poligono: "Bronce", descripcion: "Morelos Cuautla", clasificacionId: 1 },
  { ciudad: "Cuernavaca", nivel_poligono: "Oro", descripcion: "Morelos Norte", clasificacionId: 3 },
  { ciudad: "Cuernavaca", nivel_poligono: "Plata", descripcion: "Morelos Sur", clasificacionId: 2 },
  { ciudad: "Allende", nivel_poligono: "Plata", descripcion: "N.L. Allende", clasificacionId: 2 },
  { ciudad: "Apodaca", nivel_poligono: "Oro", descripcion: "N.L. Apodaca", clasificacionId: 3 },
  { ciudad: "Monterrey", nivel_poligono: "Oro", descripcion: "N.L. Carretera Nac.", clasificacionId: 3 },
  { ciudad: "Monterrey", nivel_poligono: "Oro", descripcion: "N.L. Country", clasificacionId: 3 },
  { ciudad: "Monterrey", nivel_poligono: "Oro", descripcion: "N.L. Cumbres", clasificacionId: 3 },
  { ciudad: "San Nicolás", nivel_poligono: "Plata", descripcion: "N.L. San Nicolás", clasificacionId: 2 },
  { ciudad: "San Pedro", nivel_poligono: "Platino", descripcion: "N.L. San Pedro", clasificacionId: 4 },
  { ciudad: "Monterrey", nivel_poligono: "Plata", descripcion: "N.L. Santa Catarina", clasificacionId: 2 },
  { ciudad: "Monterrey", nivel_poligono: "Platino", descripcion: "N.L. Monterrey", clasificacionId: 4 },
  { ciudad: "CDMX", nivel_poligono: "Oro", descripcion: "Narvarte Oriente, Cdmx", clasificacionId: 3 },
  { ciudad: "CDMX", nivel_poligono: "Plata", descripcion: "Narvarte Poniente, Cdmx", clasificacionId: 2 },
  { ciudad: "CDMX", nivel_poligono: "Plata", descripcion: "Naucalpan Poniente, Cdmx", clasificacionId: 2 },
  { ciudad: "Navojoa", nivel_poligono: "Plata", descripcion: "Navojoa", clasificacionId: 2 },
  { ciudad: "CDMX", nivel_poligono: "Plata", descripcion: "Nucalpan Oriente, Cdmx", clasificacionId: 2 },
  { ciudad: "Oaxaca", nivel_poligono: "Oro", descripcion: "Oaxaca Cap. Norte", clasificacionId: 3 },
  { ciudad: "Oaxaca", nivel_poligono: "Plata", descripcion: "Oaxaca Cap. Sur", clasificacionId: 2 },
  { ciudad: "Obregon", nivel_poligono: "Bronce", descripcion: "Obregón", clasificacionId: 1 },
  { ciudad: "Obregon", nivel_poligono: "Plata", descripcion: "Obregón", clasificacionId: 2 },
  { ciudad: "Orizaba", nivel_poligono: "Plata", descripcion: "Orizaba Norte", clasificacionId: 2 },
  { ciudad: "Orizaba", nivel_poligono: "Oro", descripcion: "Orizaba Sur", clasificacionId: 3 },
  { ciudad: "Pachuca", nivel_poligono: "Oro", descripcion: "Pachuca Este", clasificacionId: 3 },
  { ciudad: "Pachuca", nivel_poligono: "Plata", descripcion: "Pachuca Norte", clasificacionId: 2 },
  { ciudad: "Pachuca", nivel_poligono: "Plata", descripcion: "Pachuca Oeste", clasificacionId: 2 },
  { ciudad: "Pachuca", nivel_poligono: "Plata", descripcion: "Pachuca sur", clasificacionId: 2 },
  { ciudad: "Playa del Carmen", nivel_poligono: "Plata", descripcion: "Playa del Carmen", clasificacionId: 2 },
  { ciudad: "CDMX", nivel_poligono: "Platino", descripcion: "Polanco, Cdmx", clasificacionId: 4 },
  { ciudad: "Poza Rica", nivel_poligono: "Plata", descripcion: "Poza Rica", clasificacionId: 2 },
  { ciudad: "Puebla", nivel_poligono: "Oro", descripcion: "Puebla Centro", clasificacionId: 3 },
  { ciudad: "Puebla", nivel_poligono: "Oro", descripcion: "Puebla Centroeste", clasificacionId: 3 },
  { ciudad: "Puebla", nivel_poligono: "Plata", descripcion: "Puebla Este", clasificacionId: 2 },
  { ciudad: "Puebla", nivel_poligono: "Oro", descripcion: "Puebla Norte", clasificacionId: 3 },
  { ciudad: "Puebla", nivel_poligono: "Platino", descripcion: "Puebla Sur", clasificacionId: 4 },
  { ciudad: "Puebla", nivel_poligono: "Plata", descripcion: "Puebla Sureste", clasificacionId: 2 },
  { ciudad: "Querétaro", nivel_poligono: "Platino", descripcion: "Querétaro Centro", clasificacionId: 4 },
  { ciudad: "Querétaro", nivel_poligono: "Plata", descripcion: "Querétaro Centro/Norte", clasificacionId: 2 },
  { ciudad: "Querétaro", nivel_poligono: "Platino", descripcion: "Querétaro Diamante Este", clasificacionId: 4 },
  { ciudad: "Querétaro", nivel_poligono: "Platino", descripcion: "Querétaro Noroeste", clasificacionId: 4 },
  { ciudad: "Querétaro", nivel_poligono: "Plata", descripcion: "Querétaro Norte", clasificacionId: 2 },
  { ciudad: "Querétaro", nivel_poligono: "Oro", descripcion: "Querétaro Sur", clasificacionId: 3 },
  { ciudad: "Reynosa", nivel_poligono: "Bronce", descripcion: "Reynosa", clasificacionId: 1 },
  { ciudad: "Rio Verde", nivel_poligono: "Bronce", descripcion: "Rio Verde", clasificacionId: 1 },
  { ciudad: "CDMX", nivel_poligono: "Oro", descripcion: "Roma, Cdmx", clasificacionId: 3 },
  { ciudad: "Salina Cruz", nivel_poligono: "Plata", descripcion: "Salina Cruz", clasificacionId: 2 },
  { ciudad: "Saltillo", nivel_poligono: "Oro", descripcion: "Saltillo Norte", clasificacionId: 3 },
  { ciudad: "Saltillo", nivel_poligono: "Plata", descripcion: "Saltillo Sur", clasificacionId: 2 },
  { ciudad: "CDMX", nivel_poligono: "Oro", descripcion: "San Angel Cdmx", clasificacionId: 3 },
  { ciudad: "San Cristobal", nivel_poligono: "Plata", descripcion: "San Cristobal Norte", clasificacionId: 2 },
  { ciudad: "Tapachula", nivel_poligono: "Plata", descripcion: "San cristobal Sur", clasificacionId: 2 },
  { ciudad: "San Juan de los Lagos", nivel_poligono: "Plata", descripcion: "San Juan de los Lagos", clasificacionId: 2 },
  { ciudad: "San Juan del Rio", nivel_poligono: "Plata", descripcion: "San Juan del Rio", clasificacionId: 2 },
  { ciudad: "San Luis Potosí", nivel_poligono: "Oro", descripcion: "San Luis Potosí", clasificacionId: 3 },
  { ciudad: "San Luis Potosí", nivel_poligono: "Oro", descripcion: "San Luis Potosí", clasificacionId: 3 },
  { ciudad: "San Luis Potosí", nivel_poligono: "Oro", descripcion: "San Luis Potosí", clasificacionId: 3 },
  { ciudad: "San Luis Potosí", nivel_poligono: "Plata", descripcion: "San Luis Potosí", clasificacionId: 2 },
  { ciudad: "San Luis Potosí", nivel_poligono: "Plata", descripcion: "San Luis Potosí", clasificacionId: 2 },
  { ciudad: "San Luis Potosí", nivel_poligono: "Plata", descripcion: "San Luis Potosí", clasificacionId: 2 },
  { ciudad: "San Luis Potosi", nivel_poligono: "Platino", descripcion: "San Luis Potosí", clasificacionId: 4 },
  { ciudad: "San Miguel Allende", nivel_poligono: "Plata", descripcion: "San Miguel Allende Centro", clasificacionId: 2 },
  { ciudad: "San Miguel Allende", nivel_poligono: "Plata", descripcion: "San Miguel Allende Noreste", clasificacionId: 2 },
  { ciudad: "San Miguel Allende", nivel_poligono: "Plata", descripcion: "San Miguel Allende Norte", clasificacionId: 2 },
  { ciudad: "San Miguel Allende", nivel_poligono: "Plata", descripcion: "San Miguel Allende Sur", clasificacionId: 2 },
  { ciudad: "CDMX", nivel_poligono: "Platino", descripcion: "Santa Fé Norte", clasificacionId: 4 },
  { ciudad: "CDMX", nivel_poligono: "Platino", descripcion: "Santa Fé Sur", clasificacionId: 4 },
  { ciudad: "Tampico", nivel_poligono: "Plata", descripcion: "Tampico", clasificacionId: 2 },
  { ciudad: "Comitan", nivel_poligono: "Plata", descripcion: "Tapachula", clasificacionId: 2 },
  { ciudad: "Tepatitlan", nivel_poligono: "Plata", descripcion: "Tepatitlan", clasificacionId: 2 },
  { ciudad: "CDMX", nivel_poligono: "Plata", descripcion: "Tepeyac, Cdmx", clasificacionId: 2 },
  { ciudad: "Tepic", nivel_poligono: "Bronce", descripcion: "Tepic Este", clasificacionId: 1 },
  { ciudad: "Tepic", nivel_poligono: "Plata", descripcion: "Tepic Norte", clasificacionId: 2 },
  { ciudad: "Tepic", nivel_poligono: "Plata", descripcion: "Tepic Oeste", clasificacionId: 2 },
  { ciudad: "Tepic", nivel_poligono: "Plata", descripcion: "Tepic Sur", clasificacionId: 2 },
  { ciudad: "Tepic", nivel_poligono: "Plata", descripcion: "Tepic Sureste", clasificacionId: 2 },
  { ciudad: "Edo. Mex", nivel_poligono: "Plata", descripcion: "Tequixquiac, Edo.Méx.", clasificacionId: 2 },
  { ciudad: "Tezontepec", nivel_poligono: "Bronce", descripcion: "Tezontepec", clasificacionId: 1 },
  { ciudad: "Tlaxiaco", nivel_poligono: "Plata", descripcion: "Tlaxiaco", clasificacionId: 2 },
  { ciudad: "Torreón", nivel_poligono: "Plata", descripcion: "Torreón Oriente", clasificacionId: 2 },
  { ciudad: "Torreón", nivel_poligono: "Oro", descripcion: "Torreón Poniente", clasificacionId: 3 },
  { ciudad: "Tula", nivel_poligono: "Plata", descripcion: "Tula", clasificacionId: 2 },
  { ciudad: "Tuxpan", nivel_poligono: "Bronce", descripcion: "Tuxpan Guerrero", clasificacionId: 1 },
  { ciudad: "Tuxtla Gutierrez", nivel_poligono: "Plata", descripcion: "Tuxtla Norte", clasificacionId: 2 },
  { ciudad: "Tuxtla Gutierrez", nivel_poligono: "Plata", descripcion: "Tuxtla Sur", clasificacionId: 2 },
  { ciudad: "Tuxtla Ver.", nivel_poligono: "Bronce", descripcion: "Tuxtla Ver.", clasificacionId: 1 },
  { ciudad: "CDMX", nivel_poligono: "Oro", descripcion: "Universidad, Cdmx", clasificacionId: 3 },
  { ciudad: "Vallarta", nivel_poligono: "Plata", descripcion: "Vallarta Centro", clasificacionId: 2 },
  { ciudad: "Vallarta", nivel_poligono: "Plata", descripcion: "Vallarta Este", clasificacionId: 2 },
  { ciudad: "Vallarta", nivel_poligono: "Plata", descripcion: "Vallarta Norte", clasificacionId: 2 },
  { ciudad: "CDMX", nivel_poligono: "Oro", descripcion: "Valle de Bravo, Oriente", clasificacionId: 3 },
  { ciudad: "CDMX", nivel_poligono: "Oro", descripcion: "Valle de Bravo, Poniente", clasificacionId: 3 },
  { ciudad: "Veracruz Pto.", nivel_poligono: "Plata", descripcion: "Veracruz Pto.", clasificacionId: 2 },
  { ciudad: "Villahermosa", nivel_poligono: "Oro", descripcion: "Villahermosa", clasificacionId: 3 },
  { ciudad: "Xalapa", nivel_poligono: "Plata", descripcion: "Xalapa Norte", clasificacionId: 2 },
  { ciudad: "Xalapa", nivel_poligono: "Oro", descripcion: "Xalapa Sur", clasificacionId: 3 },
  { ciudad: "Zacatecas", nivel_poligono: "Plata", descripcion: "Zacatecas", clasificacionId: 2 },
  { ciudad: "Zamora", nivel_poligono: "Plata", descripcion: "Zamora Norte", clasificacionId: 2 },
  { ciudad: "Zamora", nivel_poligono: "Plata", descripcion: "Zamora Sur", clasificacionId: 2 },
  { ciudad: "Zihuatanejo", nivel_poligono: "Bronce", descripcion: "Zihuatanejo", clasificacionId: 1 }
];