export interface ProgramaEspecialImpulso{
    descripcion: string,
    valor: string
}

export const LISTA_PROGRAMA_ESPECIAL_IMPULSO: ProgramaEspecialImpulso[] = [
    { 
        descripcion: "PROGRAMA DE BICICLETAS ELÉCTRICAS", 
        valor: "CONSISTE EN REALIZAR LA COMPRA DE AL MENOS 1 Y COMO MÁXIMO 6 BICICLETAS E-RIDE O E-BIKES DURANTE EL PERIODO DE JULIO DE 2026 A DICIEMBRE DE 2026, COMO PARTE DEL PROGRAMA DE BICICLETAS DEMO Y PARA FOMENTAR EL USO DE BICICLETAS ELÉCTRICAS. BENEFICIOS: LÍNEA DE CRÉDITO ADICIONAL** A LA LÍNEA DE CRÉDITO ACTUAL (LIMITADA A UN MÁXIMO DEL 50 % DEL MONTO DE LA LÍNEA ACTUAL). APLICA PARA BICICLETAS NUEVAS GAMA 2027. 40 % DE DESCUENTO SOBRE EL PRECIO AL PÚBLICO. PLAZO ESPECIAL DE PAGO DE HASTA 10 MENSUALIDADES."
    },
    { 
        descripcion: "APPAREL SCOTT", 
        valor: "CONSISTE EN IMPULSAR TODAS LAS LÍNEAS DE APPAREL (ROPA, ZAPATOS, CASCOS, GUANTES, LENTES, PROTECCIONES, BOLSAS Y MOCHILAS) DESDE EL INICIO DE LA TEMPORADA A TRAVÉS DE SU EXHIBICIÓN Y DISPONIBILIDAD EN LOS PUNTOS DE VENTA. BENEFICIOS: LÍNEA DE CRÉDITO ADICIONAL** A LA LÍNEA DE CRÉDITO ACTUAL PARA LA COMPRA DE APPAREL EN TODAS SUS LÍNEAS (ROPA, ZAPATOS, CASCOS, GUANTES, LENTES, PROTECCIONES, BOLSAS Y MOCHILAS), POR UN IMPORTE EQUIVALENTE AL 50 % DE LA COMPRA MÍNIMA DE APPAREL ESTIPULADA PARA CADA NIVEL DE DISTRIBUIDOR. PLAZO ESPECIAL DE PAGO DE 60, 90 O 120 DÍAS."
    },
    { 
        descripcion: "PROGRAMA COMPRA DE EMPLEADOS", 
        valor: "CON LA FINALIDAD DE APOYAR A LA FUERZA DE VENTAS PARA ADQUIRIR EQUIPO DE LA MARCA SCOTT, OFRECEMOS EL PROGRAMA DE COMPRA DE BICICLETAS Y EQUIPO PARA EMPLEADOS, EL CUAL CONSISTE EN: 43 % DE DESCUENTO SOBRE EL PRECIO AL PÚBLICO EN LA COMPRA DE HASTA UNA BICICLETA POR TEMPORADA, UN CASCO, DOS PARES DE RUEDAS Y UN PAR DE ZAPATOS."
    },
]