export interface RestriccionPrograma{
    descripcion: string,
    valor: string
}

export const LISTA_RESTRICCIONES_PROGRAMA: RestriccionPrograma[] = [
    { 
        descripcion: "CAMBIO DE NIVEL DE DISTRIBUCIÓN A UN NIVEL INFERIOR" , 
        valor: "SI, POR MOTIVO DE INCUMPLIMIENTO O POR DESEO DEL DISTRIBUIDOR, SE CAMBIA A UN NIVEL INFERIOR Y DICHO CAMBIO ES POSTERIOR A LA FINALIZACIÓN DEL PRIMER BLOQUE, EL DISTRIBUIDOR PIERDE EL DERECHO A OBTENER LOS DESCUENTOS RETROACTIVOS ANUALES. SI EL CAMBIO SE EFECTÚA ANTES DE FINALIZAR EL PRIMER BLOQUE, DEBERÁ CUMPLIR CON LOS REQUISITOS DE LA CATEGORÍA A LA QUE SE ESTÁ CAMBIANDO."
    },
    { 
        descripcion: "CAMBIO DE NIVEL DE DISTRIBUCIÓN A UN NIVEL SUPERIOR:" , 
        valor: "EN LOS CASOS EN QUE EL DISTRIBUIDOR DECIDA CAMBIAR A UN NIVEL SUPERIOR, PODRÁ HACERLO EN CUALQUIER MOMENTO Y DEBERÁ CUMPLIR CON LOS REQUISITOS DE LA CATEGORÍA SUPERIOR PARA ACCEDER A LOS DESCUENTOS RETROACTIVOS."
    },
    { 
        descripcion: "PRECIOS DE LAS PAQUETERÍAS:",
        valor: "LAS TARIFAS DE LAS PAQUETERÍAS NORMALMENTE SE NEGOCIAN A PRINCIPIOS DE CADA TEMPORADA Y, POR LO GENERAL, PERMANECEN VIGENTES DURANTE TODO EL PERIODO. SIN EMBARGO, EN LOS ÚLTIMOS MESES ESTA SITUACIÓN HA CAMBIADO Y, EN OCASIONES, LOS COSTOS SE HAN INCREMENTADO CONSIDERABLEMENTE. POR LO TANTO, EN CASO DE PRESENTARSE UN AUMENTO IMPORTANTE, TENDREMOS QUE REFLEJARLO EN LOS PRECIOS COBRADOS. EL OBJETIVO DEL PROGRAMA DE SUBSIDIO A LOS COSTOS DE LOS FLETES ES MEJORAR NUESTRA OFERTA DE NEGOCIO Y LOGRAR QUE LA RENTABILIDAD QUE OFRECE ELITE BIKE SEA CADA TEMPORADA MAYOR." 
    },
    { 
        descripcion: "SUBSIDIO A SEGURO DE TRANSPORTE:", 
        valor: "EN LA PRESENTE TEMPORADA, EN ALGUNOS NIVELES DE DISTRIBUCIÓN, SE SUBSIDIA AL 100 % EL COSTO COBRADO POR CONCEPTO DE SEGURO DE TRANSPORTE. PARA CONOCER LAS CONDICIONES RELACIONADAS CON LOS RIESGOS DE TRÁNSITO, DEBES CONSULTAR NUESTRAS POLÍTICAS DE VENTA."
    },
    { 
        descripcion: "DESCUENTO POR PRE-PAGO O PAGO DE CONTADO:", 
        valor: "ESTE DESCUENTO SE OTORGA MEDIANTE UNA NOTA DE CRÉDITO, DÍAS DESPUÉS DE HABER REALIZADO LA COMPRA O EL PAGO. NO FORMA PARTE DE LOS DESCUENTOS RETROACTIVOS."
    },
]